version: '3'

services:
  db:
    # https://hub.docker.com/_/mysql/ 
    # or mariadb https://hub.docker.com/_/mariadb
    image: mysql:latest 
    container_name: 'mysql-${C_NAME}'
    ports:
      # change ip if required in the .env file
      - ${IP}:3306:${PORT_DB}
        # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"  
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
  wp:
    # https://hub.docker.com/_/wordpress/
    image: wordpress:latest 
    depends_on:
      - db
    container_name: 'wp-${C_NAME}'
    # https://akrabat.com/developing-wordpress-sites-with-docker/
    #build:
    #  context: ./docker
    #  dockerfile: Dockerfile-wp
    ports:
      - ${IP}:80:${PORT_WP}
    restart: always
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- wp_data:/var/www/html
      #- ./site:/var/www/html/
      #- wpdata:/var/www/html
     
     
     # - ./wp-data:/var/www/html
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DEBUG: 0
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'pma-${C_NAME}'
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:${PORT_PMA}
    links:
      - db:db

    # vstm: The sleep 10 is required so that the command is run after
    # mysql is initialized. Depending on your machine this might take
    # longer or it can go faster.
    # vstm: add shared volume
#    volumes:
      #- wp_data:/var/www/html
#      - ./site:/var/www/html/
      #- ./wp-app:/var/www/html # Full wordpress project
      #- wp_data:/var/www/html
      #- ./wp-app:/var/www/html # Full wordpress project
      #- ./wp-content/:/var/www/html/wp-content/
      #wpcli:
  #  image: wordpress:cli
  #  volumes:
  #    - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
  #    - ./wp-app:/var/www/html
  #  depends_on:
  #    - db
  #    - wp
volumes:
  db_data: {}
  db:
  wp:
  # vstm: add shared volume
  #wp_data:
  wpdata:
  
